# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kikundispringboot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - name: Setup java 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build --scan
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: azure/docker-login@v1

      with:
        username: ${{ secrets.AzureUser }}
        password: ${{ secrets.AzurePass }}
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        run: |
          docker build . -t kikundicontainerregistry.azurecr.io/test:${{ github.sha }}
          docker push kikundicontainerregistry.azurecr.io/test:${{ github.sha }}

#
#    - name: 'Login via Azure CLI'
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.ACR_CREDENTIAL }}
#      env: # Or as an environment variable
#        credentials: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login
#          az cache purge
#          az account clear
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: aci-testapp
        location: 'east us'
#
#    - name: Build and push container image to registry
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0131d1cc52dd4cff874731de42fd97ff }}/kikundi_backend:${{ github.sha }}
#        file: ./Dockerfile
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#    - name: Deploy to Azure Web App
#      id: deploy-to-webapp
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'kikundispringboot'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd539b96ba664110a144789e98df04dc }}
#        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0131d1cc52dd4cff874731de42fd97ff }}/kikundi_backend:${{ github.sha }}'